### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by fdietze** [broofa/checkcss#4]
Thanks for this tool!

I noticed that it reports a few false positives (classes which do apply styles):
- `w-[32px]`
- `left-1/2`

**Comment by broofa** [comment]
Where are those classes defined (file?), and how are they pulled into the web page?

Ideally, if you could create a small test case - a GH repo or CodePen, for example - demonstrating the problem, that would be helpful.  Thanks!

**Comment by fdietze** [comment]
Those classes are coming from tailwindCSS.
I tried to reproduce using a CodePen, but I can't get checkcss to work properly there: https://codepen.io/fdietze/pen/ZERZzME

I guess the problem lies in the escaping of special characters in the css file.

**Comment by broofa** [comment]
There's actually a lot to comment on here, so bear with me ... :-)

First, I checked out your pen and stepped through what checkCSS() is doing and I think it's working as expected.  `checkCSS()` scans the included stylesheets for classes and properly extracts the names of both `w-[32px]` and `left-1/2`.   So no issues there. (FWIW, I do see a warning about "Undefined CSS class: INLINE_PEN_STYLESHEET_ID", but that's an issue on CodePen's side of things.  Not relevant here.)

Second, I actually did a pass on Tailwind support last year that (at the time) was pretty comprehensive. See #2 .  That PR added [this unit test for Tailwind class patterns](https://github.com/broofa/checkcss/blob/main/test/test.js#L10), which I put together by distilling *all* of the class selectors Tailwind used down to a set of common patterns.  The resulting regex is "pretty good" and, as your pen shows, does seem to properly detect those classnames.  So no issues there.

Third... is `w-[32px]` actually a valid Tailwind selector?  [Should that be `w-32`](https://tailwindcss.com/docs/width#fixed-widths), for example?  If you could point me to their docs where they talk about that particular notation, I'd like to see what they say.  Sorry, I'm not that familiar with Tailwind.  Regardless, both seem to work, and be properly detected by `checkCSS()`.🤷 

[I forked your pen and played around with it a little](https://codepen.io/broofa/pen/RwJOaPK?editors=1000).  The main thing I did was pull in the actual Tailwind module from their CDN rather than defining ad-hoc classes. (See pen Settings -> JS -> Add External Scripts/Pens).  I then played around with the classnames to create slightly more complex example, adding both valid and invalid classnames.

The upshot of that is... `checkCSS()` seems to be working fine.  It stays silent for classnames that Tailwind defines, including the two you've mentioned, and complains about those that it doesn't.

Feel free to play around with that Pen to see if you can break checkCSS().  Let me know what you find.  In the meantime I'm going to close this issue, as things appear to be working correctly.

![CleanShot 2022-12-09 at 07 36 25@2x](https://user-images.githubusercontent.com/164050/206738250-45c1ca04-a243-4ec6-9c30-0963d59102b8.png)

**Comment by fdietze** [comment]
Sorry, I saw this a bit too late. The relevant Tailwind doc for `w-[32px]` is here: https://tailwindcss.com/docs/width#arbitrary-values

I just checked again on my project on localhost with the approach from #1.

The classes `w-[495px]` and `w-3/4` define styles and are used in the dom, but listed by checkcss:

![2022-12-23_12-22](https://user-images.githubusercontent.com/1186516/209587738-171b16b4-7c40-4228-84f8-ca2df031a602.png)
![2022-12-26_17-15](https://user-images.githubusercontent.com/1186516/209587930-c56f4b0b-3450-4c90-8070-4606889328fd.png)
![2022-12-26_17-11](https://user-images.githubusercontent.com/1186516/209587933-ca107234-16e2-4a0b-b496-137e5010588e.png)

**Comment by broofa** [comment]
@fdietze: Can you try updating to the latest version (2.0.4) to see if this fixes your problem here? I did a bit of a rewrite to improve the logic that detects changes to the DOM and stylesheets, and I think (?) the issue here should be resolved.

For example: I've updated [this pen](https://codepen.io/broofa/pen/RwJOaPK) to use the new version and it no longer warns about the `w-[123px]` class.
